version: '2'
services:

  kosmtik-orig:
    image: osm-carto/kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=db
      - PGUSER=postgres

  kosmtik:
    image: restjohn/kosmtik:latest
    build:
      context: ../docker-kosmtik
    volumes:
      - .:/opt/project
    ports:
      - "127.0.0.1:6789:6789"
    command: [--host, "0.0.0.0", project.mml]

  osm-bright:
    image: restjohn/kosmtik:latest
    build:
      context: ../docker-kosmtik
    volumes:
      - ../mapbox/osm-bright/osm-bright:/opt/project
    ports:
      - "127.0.0.1:6789:6789"
    command: [--host, "0.0.0.0", osm-bright.osm2pgsql.mml]

  osm-utils:
    image: restjohn/mapnik-python:latest
    build:
      context: ../openstreetmap/mapnik-stylesheets
    volumes:
      - .:/openstreetmap-carto
      - ../openstreetmap/mapnik-stylesheets:/osm-utils
    entrypoint: ["bash"]

  db:
    image: db:v1
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM

  import:
    image: import:v1
    build:
      context: .
      dockerfile: Dockerfile.import
    volumes:
      - .:/openstreetmap-carto
    depends_on:
      - db
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE
